profile_project/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/create/$', views.create_profile, name='create_profile'),
    url(r'profile/edit_password/(?P<pk>\d+)/$', views.edit_password, name='edit_password'),
    url(r'profile/view/(?P<pk>\d+)/$', views.view_profile, name='view_profile'),
    url(r'profile/edit/(?P<pk>\d+)/$', views.edit_profile, name='edit_profile'),


]

profile_project/project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

profile_project/accounts/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    date_of_birth = models.DateField()
    bio = models.TextField()
    avatar = models.ImageField(default='images/default.jpg', upload_to='images/')

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('accounts:view_profile', kwargs={'pk': self.user.pk})

profile_project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

from . import models


class ProfileForm(forms.ModelForm):
    verify_email = forms.EmailField(label='Verify email: ')
    bio = forms.CharField(widget=forms.Textarea(attrs={'id': 'mytextarea'}), min_length=10)

    class Meta:
        model = models.Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'verify_email',
            'date_of_birth',
            'bio',
            'avatar'
        ]
        widgets = {'date_of_birth': forms.DateInput(attrs={'id': 'datepicker'})}

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                'Both email fields are required to match.')


class NewPasswordForm(PasswordChangeForm):
    def clean_new_password1(self):
        new_password = self.cleaned_data.get('new_password1')
        print('New password:', new_password)

        if (self.user.profile.first_name.lower() in new_password.lower()
                or self.user.profile.last_name.lower() in new_password.lower()
                or self.user.username.lower() in new_password.lower()):
            raise forms.ValidationError(
                'New password cannot contain the user name or parts of the ' +
                'user’s full name, such as their first or last name.'
            )
        return new_password

profile_project/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from . import forms
from . import models


def retrieve_profile(request, pk):
    """This function retrieves the profile from the user."""
    user = get_object_or_404(models.User, pk=pk)
    profile = get_object_or_404(models.Profile, user=user)
    return profile


def sign_in(request):
    """View to let the user sign in."""
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('home')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    """View to let a user create an account and then signs them in."""
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:create_profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


def sign_out(request):
    """View that signs the user out."""
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


def create_profile(request):
    """View that lets the user create a profile."""
    form = forms.ProfileForm()

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'Profile added!')
            return HttpResponseRedirect(reverse('accounts:view_profile',
                                                kwargs={'pk': request.user.pk}))
    return render(request, 'accounts/profile_form.html', {'form': form})


def view_profile(request, pk):
    """View to let the user view the full details of there profile."""
    profile = retrieve_profile(request, pk)
    return render(request, 'accounts/view_profile.html', {'profile': profile})


def edit_profile(request, pk):
    """View that allows the user to edit there profile."""
    profile = retrieve_profile(request, pk)
    form = forms.ProfileForm(instance=profile,
                             initial={'verify_email': profile.email})

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Updated profile successfully!')
            return HttpResponseRedirect(profile.get_absolute_url())
    return render(request, 'accounts/profile_form.html', {'form': form})


def edit_password(request, pk):
    """View that lets the user edit there password."""
    user = get_object_or_404(models.User, pk=pk)
    form = forms.NewPasswordForm(user)

    if request.method == 'POST':
        form = forms.NewPasswordForm(user, data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['new_password1']
            )
            login(request, user)
            messages.success(
                request,
                "Password has been changed successfully."
            )
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'accounts/edit_password.html', {'form': form})

profile_project/project_7/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

profile_project/accounts/templates/accounts/edit_password.html
{% extends "layout.html" %}

{% block title %}Edit Password | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:edit_password' pk=user.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Update">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/password_change.html
{% extends "layout.html" %}

{% block title %}Password Change | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:password_change' pk=user.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Update">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/profile_form.html
{% extends "layout.html" %}

{% block title %}
  {% if user.profile %}Edit Profile{% else %}Create Profile{% endif %}
{% endblock %}

{% block body %}
{% if user.profile %}
  <h1>Edit Profile</h1>
{% else %}
  <h1>Create Profile</h1>
{% endif %}
<form enctype="multipart/form-data" method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Submit">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/view_profile.html
{% extends 'home.html' %}

{% block title %}Profile Detail{% endblock %}

{% block body %}
<div class="grid-75">
  <h1>Profile Details</h1>
  <ul class="circle--group--list">
    <li>First Name: {{ profile.first_name }}</li>
    <li>Last Name: {{ profile.last_name }}</li>
    <li>Email: {{ profile.email }}</li>
    <li>Date of Birth: {{ profile.date_of_birth }}</li>
    <li>Biography: {{ profile.bio|safe }}</li>
    <img class="circle--primary--avatar" src="{{ profile.avatar.url }}">
  </ul>
</div>

{% endblock %}

profile_project/templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-75">
      {% if not user.is_authenticated %}
        <h1>Welcome to the Profile Project!</h1>
        <p>Sign up to create a profile or sign in to view your profile.</p>
      {% else %}
        {% if user.profile %}
          <h1>Welcome {{ user.profile }} to your profile.</h1>
          <ul class="circle--group--list">
            <li>First Name: {{ user.profile.first_name }}</li>
            <li>Last Name: {{ user.profile.last_name }}</li>
            <li><a href="{% url 'accounts:view_profile' pk=user.pk %}">View Full Profile</a></li>
          </ul>
        {% else %}
          <h1>Welcom {{ user }}!</h1>
          <p>Create a profile to view <a href="{% url 'accounts:create_profile' %}">here.</a></p>
        {% endif %}
      {% endif %}
    </div>
{% endblock %}

profile_project/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href = "https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"
         rel = "stylesheet">
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
            integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.2/tinymce.min.js'
            referrerpolicy="origin"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>

    <!-- Javascript for datepicker from https://api.jqueryui.com/datepicker/-->
    <script>
       $(function() {
          $( "#datepicker" ).datepicker();
       });
    </script>

    <!-- Javascript for texteditor from https://www.tiny.cloud/-->
    <script>
    tinymce.init({
      selector: '#mytextarea',
      height: 250,
      menubar: false,
      toolbar: 'undo redo | formatselect | bold underline italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat',
      content_css: [
        '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
        '//www.tiny.cloud/css/codepen.min.css'
      ]
    });
    </script>

</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.profile %}
                          <li><a href="{% url 'accounts:view_profile' pk=user.pk %}">View Profile</a></li>
                          <li><a href="{% url 'accounts:edit_profile' pk=user.pk %}">Edit Profile</a></li>
                          <li><a href="{% url 'accounts:edit_password' pk=user.pk %}">Change Password</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.is_authenticated %}
                          {% if user.profile %}
                          <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                          {% else %}
                          <li><a href="{% url 'accounts:create_profile' %}">Create Profile</a></li>
                          <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                          {% endif %}
                        {% else %}
                          <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                          <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>